### ISSUE TITLE
Slowdown when have big response body

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/http-proxy#44]
Example: 
body
```
<wfs:GetFeature service="WFS" version="1.1.0" xmlns:gml="http://www.opengis.net/gml" xmlns:wfs="http://www.opengis.net/wfs" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd"><wfs:Query typeName="lhtac:web2014all_mv" srsName="EPSG:4326"><ogc:Filter><ogc:And><ogc:Intersects><ogc:PropertyName>geom3857</ogc:PropertyName><gml:Polygon srsName="EPSG:4326"><gml:exterior><gml:LinearRing><gml:posList>-117.18017578125 47.4057852900587 -117.18017578125 47.60616304386874 -116.60888671874999 47.60616304386874 -116.60888671874999 47.4057852900587 -117.18017578125 47.4057852900587</gml:posList></gml:LinearRing></gml:exterior></gml:Polygon></ogc:Intersects><ogc:Intersects><ogc:PropertyName>geom3857</ogc:PropertyName><ogc:Function name="collectGeometries"><ogc:Function name="queryCollection"><ogc:Literal>lhtac:itd_districts</ogc:Literal><ogc:Literal>the_geom</ogc:Literal><ogc:Literal>ITD_Dist_n IN ('1')</ogc:Literal></ogc:Function></ogc:Function></ogc:Intersects></ogc:And></ogc:Filter></wfs:Query></wfs:GetFeature>
```

To this URL : 
`http://demo.geo-solutions.it/geoserver/ows?service=WFS&outputFormat=application/json&`
thakes 247ms

![image](https://cloud.githubusercontent.com/assets/1279510/20571267/0e89f5e0-b1a7-11e6-9e47-520c847ee817.png)

Using the proxy: 
`http://lhtac.geo-solutions.it/lhtac-webgis/proxy/?url=http%3A%2F%2Fdemo.geo-solutions.it%2Fgeoserver%2Fows%3Fservice%3DWFS%26outputFormat%3Dapplication%2Fjson`

Takes 6156 ms:
![image](https://cloud.githubusercontent.com/assets/1279510/20571301/317c296a-b1a7-11e6-815b-a2fce922e87a.png)

This is the full HTTP request:
```
POST /lhtac-webgis/proxy/?url=http%3A%2F%2Fdemo.geo-solutions.it%2Fgeoserver%2Fows%3Fservice%3DWFS%26outputFormat%3Dapplication%2Fjson HTTP/1.1
Host: lhtac.geo-solutions.it
Content-Type: application/xml
Accept: application/json
Cache-Control: no-cache
Postman-Token: b9978abf-28a6-fc83-9157-d3546c6c7fc9

<wfs:GetFeature service="WFS" version="1.1.0" xmlns:gml="http://www.opengis.net/gml" xmlns:wfs="http://www.opengis.net/wfs" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd"><wfs:Query typeName="lhtac:web2014all_mv" srsName="EPSG:4326"><ogc:Filter><ogc:And><ogc:Intersects><ogc:PropertyName>geom3857</ogc:PropertyName><gml:Polygon srsName="EPSG:4326"><gml:exterior><gml:LinearRing><gml:posList>-117.18017578125 47.4057852900587 -117.18017578125 47.60616304386874 -116.60888671874999 47.60616304386874 -116.60888671874999 47.4057852900587 -117.18017578125 47.4057852900587</gml:posList></gml:LinearRing></gml:exterior></gml:Polygon></ogc:Intersects><ogc:Intersects><ogc:PropertyName>geom3857</ogc:PropertyName><ogc:Function name="collectGeometries"><ogc:Function name="queryCollection"><ogc:Literal>lhtac:itd_districts</ogc:Literal><ogc:Literal>the_geom</ogc:Literal><ogc:Literal>ITD_Dist_n IN ('1')</ogc:Literal></ogc:Function></ogc:Function></ogc:Intersects></ogc:And></ogc:Filter></wfs:Query></wfs:GetFeature>
```

**Comment by simboss** [comment]
Can we get the value for the defaultStreamByteSize config param?

Is it set?

The default does not seem reasonable to me (1KB) and it might slown down large responses parsing.

**Comment by mbarto** [comment]
I think this is part of (or all) the problem:

https://github.com/geosolutions-it/http-proxy/blob/32dff1d6d8bcc95d320d0938c139a4b33a212734/src/main/java/it/geosolutions/httpproxy/HTTPProxy.java#L789-L797

Basically we read all the response in memory and then we flush it to the servlet output stream. I would simply remove the bytearrayoutputstream usage.

**Comment by simboss** [comment]
Good catch Mauro.

I think we need to:

- [ ] avoid caching the entire response in memory
- [ ] improve response reading and writing. This might mean putting NIO in the mix and/or large default size for the buffer.

**Comment by offtherailz** [comment]
Applying the fixes I noticed that the issue not visible in my local env. 
I suppose the issue is visible in production because of some bottleneck in networking from the http-proxy point of view (It can be reading the response or sending it back to the client) that can be anyway multiplied by the issue I fixed.

**Compared results with local proxy**
![image](https://cloud.githubusercontent.com/assets/1279510/20891084/9b9172ae-bb09-11e6-8cc5-697b921d8d2f.png)

So not any appreciable difference between normal and proxy request.  

*note*: The response starts in late for the proxy version. 

**Proxy response timing without fix** : 
![image](https://cloud.githubusercontent.com/assets/1279510/20892463/a2d96c88-bb0e-11e6-9e9c-137355bea37f.png)

**Of course the same for the fixes applied**:
![image](https://cloud.githubusercontent.com/assets/1279510/20891221/1ede6676-bb0a-11e6-96f4-0346e822ce5d.png)

(note: of course we can not see the difference between normal request and proxy request, so we don't expect any improvement from our changes in local tests. 

**But it starts to write the response before**: 
![image](https://cloud.githubusercontent.com/assets/1279510/20891459/fc06c408-bb0a-11e6-9119-eec8dd606d27.png)

I suggest to add my changes anyway, to improve the response timing, and then see it they reduce the problem, what do you think?

**note** I changed the buffer size in local, but of course nothing changed, I will not commit it, I'd like to do some tests in dev env instead, to see if it improves the performances too.

**Comment by simboss** [comment]
Well, the writing above is not _extremely_ clear to me.

Anyway, I would go ahead, incorporate my suggestions and do the merge.

With large responses it is a waste of memory to load everything before proxying!
