### ISSUE TITLE
http.nonProxyHosts ignored by http-proxy

### ISSUE THREAD

**Issue by randomorder** [geosolutions-it/http-proxy#47]
I  struggled a bit with the configuration of HTTP Proxy, apparently, only some of the Proxy System variables (https://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html) are picked up by http-proxy.
Specifically, http.proxyHost and http.proxyPort are working fine but it looks like **http.nonProxyHosts** is ignored.

https://github.com/geosolutions-it/http-proxy/blob/master/src/main/java/it/geosolutions/httpproxy/HTTPProxy.java#L147

**Comment by Gnafu** [comment]
This may help to remove that code block and use system properties:

http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/HttpClientBuilder.html
