### ISSUE TITLE
httpProxy not working without proxyHost-proxyPort

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/http-proxy#65]
When #27 has been implemented, now we can not use the proxy anymore, without passing the system variables `proxyHost` etc...

The normal behavior of this application should work **without** corporate proxy. The corporate proxy is an option. 

We need also to document these properties to allow their usage.

## Versions Afflicted 

1.2 and following 

## Other considerations

Moreover, accordingly with [this specification](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html) we updated to the new servlet in order to use the built-in functionalities. But the current implementation seems to update **and** re-implement the functionality internally. This, reusing also the same names of the variables accepted by, looks a little problematic.
If there is a reason for that, we need to explicitly document it in the code. I suggest anyway to re-use if possible the build-in functionality. Otherwise we are implementing a different functionality, and so we need different properties.

**Comment by tdipisa** [comment]
@nmco no, sorry. There is no project code there. The time cannot be logged under C027-COMUNE_FI-2021-SUPPORT. At this stage we have to log the time under INTERNAL/MAPSTORE,.

**Comment by nmco** [comment]
Understood, @taba90 and @shadab-geo please add a new column on your timesheet named MAPSTORE under INTERNAL, don't log this under VARIOUS or GT\GS.

**Comment by shadab-geo** [comment]
PR under review: https://github.com/geosolutions-it/http-proxy/pull/66

**Comment by nmco** [comment]
@taba90 we need a review form you on this.

**Comment by taba90** [comment]
the pr was merged on master. @tdipisa  let me know if we can backport or you want before to do some tests.

**Comment by tdipisa** [comment]
Thank you @taba90. Please confirm the MVN repo is updated so that we can proceed to change the dependency in MS master to 1.3-SNAPSHOT to test this fix.

**Comment by taba90** [comment]
@tdipisa maven repo is updated with the latest 1.3-SNAPSHOT coming from the master  branch

**Comment by tdipisa** [comment]
Thank you so much @taba90.
Can you please remove also the 1.3.0 tag as we agreed?

**Comment by taba90** [comment]
tag deleted

**Comment by tdipisa** [comment]
@taba90 1.3-SNAPSHOT still has problems it seems. I've reported the result of my test in https://github.com/geosolutions-it/MapStore2/issues/7950#issuecomment-1079045922

**Comment by nmco** [comment]
What's the status of this?

**Comment by tdipisa** [comment]
@nmco see [here](https://github.com/geosolutions-it/MapStore2/issues/7950#issuecomment-1092836366) for my last report.
